query AppPage($id: String!) {
  app(id: $id) {
    ...App
    containers {
      dockerContainer {
        dockerContainerName
        status
      }
      volumes {
        name
        variant {
          ... on AppVolumeTypeDisposableGraphQL {
            containerPath
          }

          ... on AppVolumeTypeInternalGraphQL {
            containerPath
          }

          ... on AppVolumeTypeExternalGraphQL {
            containerPath
            readonly
          }

          ... on AppVolumeTypeBindToPathGraphQL {
            containerPath
            hostPath
            readonly
          }
        }
      }
    }
    fetchedStatus
  }
}
