[package]
name = "onix-server"
version = "0.1.0"
edition = "2021"
default-run = "onix-server"

[[bin]]
name = "onix-server"
path = "src/main.rs"

[[bin]]
name = "onix-pack-store"
path = "src/bin/store_packer.rs"

[dependencies]
anyhow = "1.0.65"
async-graphql = { git = "https://github.com/ClementNerma/async-graphql-fork", branch = "feat/input-name-suffix", default-features = false, features = ["time", "log"] }
async-graphql-axum = { git = "https://github.com/ClementNerma/async-graphql-fork", branch = "feat/input-name-suffix" }
async-trait = "0.1.58"
axum = "0.5.16"
base62 = "2.0.2"
bollard = "0.13.0"
clap = { version = "4.0.15", features = ["derive"] }
dirs = "4.0.0"
env_logger = "0.9.1"
futures = "0.3.24"
log = "0.4.17"
lz4_flex = "0.9.5"
once_cell = "1.15.0"
os_pipe = "1.1.1"
paste = "1.0.9"
pomsky = "0.7.0"
pomsky-macro = "0.7.0"
rand = "0.8.5"
regex = "1.6.0"
reqwest = "0.11.12"
serde = { version = "1.0.145", features = ["derive"] }
serde_json = "1.0.87"
serde_yaml = "0.9.14"
time = { version = "0.3.15", features = ["local-offset", "serde"] }
tokio = { version = "1.21.2", features = ["macros", "rt-multi-thread", "fs"] }
tower-http = { version = "0.3.4", features = ["cors"] }
