fragment AppContainer on AppContainer {
  id
  name
  image
  envVars {
    name
    value
  }
  portBindings {
    hostPort {
      port
      portType
    }
    containerPort {
      port
      portType
    }
  }
  dependsOn
  createdOn
}
